### PR TITLE
Start of bare-bones reference manual

### PR DESCRIPTION
**Pull request by mascarenhas**
What it says on the tin. :-)

### CODE REVIEW

**Review by hishamhm — APPROVED** [review]

**Comment by hishamhm** [comment]
Yay! I actually learned something new reading it! :)

**Comment by hugomg** [comment]
Is there a particular reason why arrays default to `{integer}`?

**Comment by mascarenhas** [comment]
> Is there a particular reason why arrays default to {integer}?

Just following C as having `integer` be the default type. When we have the `lua` dynamic type it will be a better default.

It would be easy enough to have the type be `{ <unbound type variable> }` and then unify with something else when more context appeared, but things would get messy pretty fast with subtyping, and there would always be the temptation to go full H-M and dig ourselves a hole. 😄

**Comment by hishamhm** [comment]
+1 to the approach of documenting the language as the implementation currently is, and not what the language should become.

**Pull request merged**
