### PR TITLE
Should we add the benchmarks in this repository?

### PR DESCRIPTION
**Pull request by andremm**
I'm creating this PR to discuss if we should include the benchmarks in this repository. As a start I created a script that runs the `binsearch` benchmark created by @hugomg and then adapted by @mascarenhas to just print out the results for Titan, LuaJIT, and Lua. One nice thing to have one benchmark script is that it is easy to run on different machines. Later on we can improve the script to be smarter and generate the results in a better format instead of just printing them out.

### CODE REVIEW

**Comment by hishamhm** [comment]
If we decide to post these in the main repo, we need to add a disclaimer in the benchmarks readme, stating something like "these are microbenchmarks and that they should be taken with a grain of salt".

**Comment by gligneul** [comment]
I prefer to keep things organized and create a separate repo for the benchmarks.

**Comment by hugomg** [comment]
I think having a folder for benchmarks would be organized enough for me. One advantage of having everything under one repo is that the benchmarks can stay synchronized to the current language version

On Oct 24, 2017 2:21 PM, Gabriel de Quadros Ligneul <notifications@github.com> wrote:

I prefer to keep things organized and create a separate repo for the benchmarks.

**Comment by hishamhm** [comment]
We could also use it to track performance regressions eventually (though that can't be done trivially in Travis... unless we find a reliable way to track cycles in there (...running a CPU emulator like QEMU perhaps!?))

**Comment by mascarenhas** [comment]
Shouldn't `perf` work on Travis?

​

**Comment by hishamhm** [comment]
It might, we need to test. It requires CPU accounting options to be enabled in the running kernel, and I don't know if that's exposed in containerized environments. But it's just a matter of testing, really.

**Pull request closed without merging**
