### PR TITLE
[master] remove troublesome global C state from modules

### PR DESCRIPTION
**Pull request by hishamhm**
This is a rebase into `master` of PR #233.

### CODE REVIEW

**Comment by hishamhm** [comment]
@mascarenhas this made it much easier to follow! (and made me note that there was an update done to `codearray` that wasn't done in `codemap`; I updated and squashed it there — I'll probably refactor the common parts of these functions later)

**Comment by hishamhm** [comment]
I would prefer to merge this one instead (and work using this version over the weekend, until we get a chance to discuss primitives in the next meeting)

**Comment by mascarenhas** [comment]
I am fixing a couple of loose ends and will push a commit soon, and then we can merge.

**Comment by mascarenhas** [comment]
My commit addresses two issues:

* There was a bugfix for comparing two `value`s in the `primitives` branch that we should keep
* The slot indexes of a module's members must be deterministic, otherwise we cannot have separate compilation with the current scheme (we need a test for that)

**Comment by mascarenhas** [comment]
Feel free to merge this into `master`!

**Review by mascarenhas — APPROVED** [review]

**Pull request merged**
