### PR TITLE
Beginnings of foreign import support

### PR DESCRIPTION
**Pull request by hishamhm**
Still lots of stuff to add, but this already allows this code to run:

```lua
local stdio = foreign import "stdio.h"

function foo()
    local fd = stdio.fopen("hello.txt", "w")
    local msg = "Hello, Titan!\n"
    local n = stdio.fwrite(msg, #msg, 1, fd)
    local err = stdio.fclose(fd)
    if err == 0 then
        stdio.printf("All ok!\n")
    end
end
```

Merry Christmas! 🎄 🎅

### CODE REVIEW

**Comment by hishamhm** [comment]
@mascarenhas Rebased on top of `multiret`, since that branch is probably going to be the next one to be merged

**Comment by hishamhm** [comment]
This branch is currently failing on Travis because the code fails to parse the `stdlib.h` in that system (it Works On My Machine™) -- will try to check that out on a Ubuntu VM when I get the time.

**Comment by mascarenhas** [comment]
Latest commit got Travis to bless this PR, but commits since the multiret rebase made this stale and it looks like there are conflicts. Ping me if you'd like any help with those!

**Comment by hishamhm** [comment]
Thanks! But don't worry, I will clean up and rebase this tomorrow, so it
will be good for merge. The conflicts should be easy to handle, I have
resynced this branch before.

>

**Comment by hishamhm** [comment]
@mascarenhas it's good to merge!

**Review by mascarenhas — APPROVED** [review]

**Comment by mascarenhas** [comment]
It is **very** cool to see this land in master!

**Pull request merged**
